name: Docker Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub (optional if pushing)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${DOCKER_USERNAME}/comfyui-runpod-worker:latest .

      # 4️⃣ Push Docker image to Docker Hub (optional)
      - name: Push Docker image
        run: |
          docker push ${DOCKER_USERNAME}/comfyui-runpod-worker:latest
